# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
pandoc_version: 1.19.2.1

os:
  - linux
  - osx

after_failure:
  - cat $TRAVIS_BUILD_DIR/RelDists.Rcheck/00install.out
  - cat $TRAVIS_BUILD_DIR/RelDists.Rcheck/00check.log
before_install:
      - brew update
      - brew cask reinstall xquartz
      - brew install tcl-tk
      - brew link --overwrite --force tcl-tk; brew unlink tcl-tk
      - sudo tlmgr update --self
      - sudo tlmgr install framed titling